name: Run Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ main, development ]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Run benchmarks
      run: dotnet run --project BBTT/BBTT.BenchMarkingConsole/BBTT.BenchMarkingConsole.csproj --configuration Release > BenchmarkResult.txt

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results-${{ github.run_number }}
        path: BenchmarkResult.txt
